title: Thiago Cruz
email: thiago.hmcruz@gmail.com
url: "https://thiagohmcruz.me"
github_username: thiagohmcruz
linkedin_username: thiagohmcruz
twitter_username: thiagohmcruz
header_pages:
  - index.md
  - projects.md
  - contact.md
theme: minima
plugins:
  - jekyll-feed
  
