title: Thiago Cruz
email: thiago.hmcruz@gmail.com
baseurl: ""
url: "https://thiagohmcruz.me"
github_username: thiagohmcruz
linkedin_username: thiagohmcruz
twitter_username: thiagohmcruz
mastodon:
- username: thiagohmcruz
  instance: mastodon.online
header_pages:
  - index.md
  - projects.md
  - contact.md
theme: minima
plugins:
  - jekyll-feed
  
